name: markaz_snappy
description: Snapy Markaz App is a digital membership application to replace card members.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  meta: ^1.7.0
  http: ^0.13.4
  gap: ^2.0.0
  colour: ^1.0.5
  shared_preferences: ^2.0.9
  cached_network_image: ^3.1.0+1
  scrollable_positioned_list: ^0.2.3
  equatable: ^2.0.3
  get: ^4.3.8
  flutter_screenutil: ^5.6.0
  flutter_svg: ^0.21.0
  google_fonts: ^3.0.1
  cool_alert: ^1.1.0
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.7
  pin_code_text_field: ^1.8.0
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.0
  change_app_package_name: ^1.1.0

flutter_app_name:
  name: "Snapy"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_ios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/ca/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages